#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pygame import *
import os

BHEIGHT = 32
BWIDTH = 32

class Cross(sprite.Sprite):
    def __init__(self,x,y):
        self.x = 0
        self.y = 0
        self.rect = Rect(x, y, BWIDTH, BHEIGHT)

if __name__ == "__main__":
    exit(0)
